// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingApi.Data;

namespace TrainingApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20181212010150_newField")]
    partial class newField
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TrainingApi.Data.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("TrainingApi.Data.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("HomeAddress");

                    b.Property<string>("LastName");

                    b.Property<int>("Mobile");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("TrainingApi.Data.ClientExercise", b =>
                {
                    b.Property<int>("ClientExerciseId");

                    b.Property<int>("ClientWorkoutId");

                    b.Property<int>("ExerciseId");

                    b.Property<bool>("IsActive");

                    b.HasKey("ClientExerciseId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("ClientExercises");
                });

            modelBuilder.Entity("TrainingApi.Data.ClientWorkout", b =>
                {
                    b.Property<int>("ClientWorkoutId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientExerciseId");

                    b.Property<int>("ClientId");

                    b.Property<int>("Frequency");

                    b.Property<int>("WorkoutPlanId");

                    b.HasKey("ClientWorkoutId");

                    b.HasIndex("WorkoutPlanId");

                    b.ToTable("ClientWorkouts");
                });

            modelBuilder.Entity("TrainingApi.Data.Exercise", b =>
                {
                    b.Property<int>("ExerciseId");

                    b.Property<int>("CategoryId");

                    b.Property<bool>("DoNotUse");

                    b.Property<string>("Name");

                    b.Property<int>("VideoLibraryId");

                    b.HasKey("ExerciseId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("TrainingApi.Data.VideoLibrary", b =>
                {
                    b.Property<int>("VideoLibraryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AltTag");

                    b.Property<DateTime>("CreateDate");

                    b.Property<bool>("DoNotUse");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("VideoUrl");

                    b.HasKey("VideoLibraryId");

                    b.ToTable("VideoLibraries");
                });

            modelBuilder.Entity("TrainingApi.Data.WorkoutExercise", b =>
                {
                    b.Property<int>("WorkoutExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("DoNotUse");

                    b.Property<int>("ExerciseId");

                    b.Property<int>("WorkoutPlanId");

                    b.HasKey("WorkoutExerciseId");

                    b.ToTable("WorkoutExercises");
                });

            modelBuilder.Entity("TrainingApi.Data.WorkoutPlan", b =>
                {
                    b.Property<int>("WorkoutPlanId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("DoNotUse");

                    b.Property<string>("Name");

                    b.Property<string>("imageUrl");

                    b.HasKey("WorkoutPlanId");

                    b.ToTable("WorkoutPlans");
                });

            modelBuilder.Entity("TrainingApi.Data.ClientExercise", b =>
                {
                    b.HasOne("TrainingApi.Data.ClientWorkout")
                        .WithMany("ClientExercises")
                        .HasForeignKey("ClientExerciseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TrainingApi.Data.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TrainingApi.Data.ClientWorkout", b =>
                {
                    b.HasOne("TrainingApi.Data.WorkoutPlan", "WorkoutPlan")
                        .WithMany()
                        .HasForeignKey("WorkoutPlanId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TrainingApi.Data.Exercise", b =>
                {
                    b.HasOne("TrainingApi.Data.WorkoutExercise")
                        .WithMany("Exercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
